language: haskell

branches:
    only:
        - source

env:
    global:
        - GH_NAME='8ssou.travis'
        - CABAL_VERSION='1.22'
        - GHC_VERSION='7.10.3'
        - secure: "R9Y/xUe0FmM+Lm719GccqZmzCcuvEyEUj12hS7r7W1ipTUtNUBAuVtVFDLZSRENCdQy8bmT+64GLgVd7ZjwiNdF9d0unc5mAm0LwQc1RQk+s3yDCrZaPn9ygIoWom0Ojs/jRjT+kR5y0jJj0tCtQp26E3k+fYCQV5SToLT1S7Miz736N/SaJCzJ0CxHFGCzRx2iMN+qrFklWb8cGQae0PVd1zigDLGWvaClDGILcld37MqOdk2No1f5wH4U2qhNpJOSN+8+MoCo+s6n5iX7Ga5/HaUf6R2K/Z9QhwDz08ElwQWg09Vs97MsUbeBn7xjDrOCfbTesSH6sjPXyA9rAqNrtUDtt6sozqny0uQsFdme0bYDpnJhTHIGQEIMcbYu3vQrDnJUUTJ8e/tZx1BixgUq6P2KTIpvYMSv/C858oK2cXuaHeLgIhRoookfwFTChIZkN6H1uDjPmWbkeq8gHWU6VSCU0vvo++yUlstMaIJWAbnuURucdLRe0acuDXJHf7gM+WvyfeRxbOQRcHGgJT8RDXSDgnsmxF95sowIxsvwJ5CAMKtp2vnkIruSZnvgkivAOKy53fyIfX4ulV886EqdApTFO4z38Nj8Oqk25ZYZZJhvsOWw4KETjTDhzmMnUPQBMToMcN8gfltIS6GWwiQveHwO/2vUlAPFU+ohYz3I="
        - secure: "wHwqDqWjZFBWQ9dFB/5fIbJAZ/Uqz3e3fzcbwMpjH/jhDNvsQWs0I1KX67YCkinMAMCKcaIgVXOWM19MxP76WaYdU4FkmearO0iOOzek/fA8ehGoTmDgSV9NDhYja6GQ7Fn5P/CkxikI+ccelqBKMRN6KWIo800d4FQzayjTWiiRh6rh4MJ9nTtXFWzlsigxlwB6pSj/wub1ztms5lOC30nqzuxkQrU/zqSJHjK381uCwmSKCyYc3Pi9lpd8bqXTr7lqc57HzfXhxY5ozRWKMFflqwka0tjfQl6A3y4tvhNlvUQPbC7NmtDMiRPXGba8BiKuB4LusLEnHSqCTS97J1lBXONR77hCHV4vA8nM+gHPbJJXjYe9q4RU8nbcyBpcRdJWCkv38JoHMLpfdtbI2q3s2a2AciLg1PVMR+bw09JG0zY4EY6Zj8v15O2TNleqtaXqkcucr1G15ntlhM+LpZSFVPhxIMswDsn+/U4NLO88357oe0LJiRHdO56Ly6JLtmFsPHYXsPamaDRQz6NwRDdlZSOBSfqM9w4eXbKusSXM5PoY5g4rUKeiDdtARI/sXHFYInKe2o8ZMzna6ckaiHgjCzdOXAbeNsBXcw8b/0G/W7tcDgsLmVoon+0Uu7+jMZPubZpQDcAYSHFNAUv8YyluAUORcrmd0uLZeMQmQCk="

before_install:
    - travis_retry sudo apt-get install -y software-properties-common
    - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    - travis_retry sudo apt-get update -q
    - travis_retry sudo apt-get install cabal-install-${CABAL_VERSION} ghc-${GHC_VERSION}
    - export PATH=/opt/ghc/${GHC_VERSION}/bin:/opt/cabal/${CABAL_VERSION}/bin:$PATH
    - git submodule foreach --recursive 'git checkout master; git ls-files | grep -v README | grep -v CNAME | xargs -r git rm'

before_script:
    - git config --global user.name "$GH_NAME"
    - git config --global user.email "$GH_EMAIL"

install:
    - sudo rm ~/.cabal/config
    - travis_retry cabal update
    - cabal sandbox init
    - cabal install happy
    - cabal install --only-dependencies --disable-documentation --max-backjumps=-1
    - cabal configure --disable-library-profiling --disable-tests --disable-coverage --disable-benchmarks --disable-split-objs

script:
    - cabal run -j build

after_success:
    - cd _site
    - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
    - git remote add github https://${GH_TOKEN}@${REMOTE}
    - git add --all
    - git status
    - git commit -m "Built by Travis (build $TRAVIS_BUILD_NUMBER)"
    - git push --quiet github master:master
