language: haskell

branches:
    only:
        - source

env:
    global:
        - GH_NAME='8ssou.travis'
        - CABAL_VERSION='2.0.1.0'
        - GHC_VERSION='7.10.3'
        - secure: "JbaABUyPhIR0dDqdnIqrpHduWZk5kJ+oMLljSibrKMWNhFqcPZ51A18rT3ZM5O89WSFwZaG0lnp2oAY//efFw12/WRn4aVzKLpuHP0d31LuXwEXRRGcdd9i6qR0Agyoqu+x1EZzfT6yElLoPT5y5xxX7JtnNHOh0tmTY4CXH4zf2s15R5pLFBPs+YUpvjE08EceTcDzmhEYGn6BhuWkCcKfJFKQYNzCoaNI3pgDePNTBYDFydBVYP7E4+oFJ5/n4ZW7RyV74B7BrtJLbTUZKt9ox9UBHW4l213O7sXtgUJ8EmqWouL1SEiSe4nIll0bGCs+4EcRcZWFHQIUm+UqYwC0frBLFwbRx/FVjSPOSKHZiCtYAW8uR6fkID5gixpWnnoGptrSJMO3yfz396+aQ6tFyPNJtRvpaGPL/QWXDIf1SGx7WOmRd/gO8uoP89y54yBewnTOBBtXGKO2ABzwtYC/WYTsajB/AWYozstmYZQwrgRNiNwwaulGtt9pdxgp6Wtpki86iVVlpBv8wiNQI+oNK55PYKJadqKpsULqacxAITfjx5+NipErWWCFhet4+HYTcPEOQRlx2T54XTdah3y0OLjzDpHLy9SHzDb87RKhzn1IclGAZIQ98+3wQ0C1XUCGvpE8CUiHn/J1VSb43yH8itJoAtkCwBQYkftop9eM="
        - secure: "em9TmK7ARZgo8XYcqHlCxRgGUZmHqjWy3x4mP5hRHyxn8OoaMLSuBZaHdR2UKWWghrEhnCf6ppT/qQT9VwcKFZoW2TsTuTtwDoMbrdm3vA7fKpyShMw1yhNwrY7qq0imF0/bm7v2I0GUkulq+R5UWhs7xLlgEf+G+8b+mzmn4/NhKixf1ORwtV0nU8UQT5Ta+x8UFuJFUINW9GW1ch3BaGV98qfRcFVLBITRHPf3sA7aGkTmP99bBQFjzkQ2/5UuBoh0L1XI3GTvC/2VJljkcoP5dRKTRXUV94sADmofE/gl3vgGuZiVCNgerD0NkZJrN68NxoElzXVW2R/SZmW+qKl9/Gla2jA7HMRlmcDZlHA8Fq4opTIA6HFp+7+GB+MT/t8Je0MiVpjTALVJWjA1FV1DrDHM/bReWt28eUnmMYy3uQmGngIanzVZSy0TBpgEQoGB6xja6xFwPHF/2DLYJo6S+Bu0RxVWvGUjZ/qCTmc3kZF5TDfxmmHNQwfJiPZMREkBQY8m81JPP/w437dJz7OsOAo8UHcFmKhvlqHZzMe/Q3EReHAX4Wwx+x/5AgOT2JYdyE/G5SwZPIdoEM5qVl8KNizZ85IOQcQ8x3IXsFsJrr2VmVRnUw1IwUzn5YsshNI1PLayAz3LYcbSnN4cw0AffQXZzAvUij2q9t6eEyY="

before_install:
    - travis_retry sudo apt-get install -y software-properties-common
    - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    - travis_retry sudo apt-get update -q
    - travis_retry sudo apt-get install cabal-install-${CABAL_VERSION} ghc-${GHC_VERSION}
    - export PATH=/opt/ghc/${GHC_VERSION}/bin:/opt/cabal/${CABAL_VERSION}/bin:$PATH
    - git submodule foreach --recursive 'git checkout master; git ls-files | grep -v README | grep -v CNAME | xargs -r git rm'

before_script:
    - git config --global user.name "$GH_NAME"
    - git config --global user.email "$GH_EMAIL"

install:
    - sudo rm ~/.cabal/config
    - travis_retry cabal update
    - cabal sandbox init
    - cabal install --only-dependencies --disable-documentation --max-backjumps=-1
    - cabal configure --disable-library-profiling --disable-tests --disable-coverage --disable-benchmarks --disable-split-objs

script:
    - cabal run -j build

after_success:
    - cd _site
    - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
    - git remote add github https://${GH_TOKEN}@${REMOTE}
    - git add --all
    - git status
    - git commit -m "Built by Travis (build $TRAVIS_BUILD_NUMBER)"
    - git push --quiet github master:master
